# -*- coding: utf-8 -*-
"""인플루언서_통합_2차.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaN168y3cl4Jha2fUwkb9u8E51cT6fn6
"""

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = '/content/drive/MyDrive/2조_누구냐, 넌!/04. 기타자료/인플루언서 통합 2차/'

import pandas as pd
import numpy as np
import re

df_1 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_김현경.csv")
df_2 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_박경봉.csv")
df_3 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_박지혜_운동.csv")
df_4 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_박지혜_반려동물.csv")
df_5 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_이동규.csv")
df_6 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_최성진_패션.csv")
df_7 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_최성진_인테리어.csv")
df_8 = pd.read_csv(f"{DATA_PATH}인플루언서_통합_2차_한수길.csv")

df_5 = df_5.drop(columns = ['Unnamed: 0'])

df_8 = df_8.iloc[:,1:8]

df_str = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8]).reset_index(drop=True)
df_str

df_str = df_str.drop_duplicates(['content']).reset_index(drop=True)

df_str = df_str.drop(index = 1300).reset_index(drop=True)

df_lst = df_str.copy()

df_lst['comments'] = df_lst['comments'].str.replace('[\[\]]', '', regex=True).str.replace(', ', '')
df_lst['username'] = df_lst['username'].str.replace('[\[\]]', '', regex=True).str.replace(', ', '')
df_lst['tags'] = df_lst['tags'].str.replace('[\[\]]', '', regex=True).str.replace(', ', '')

df_lst

df_lst.loc[df_lst['comments'] == '', 'comments'] = np.nan
df_lst.loc[df_lst['username'] == '', 'username'] = np.nan
df_lst.loc[df_lst['tags'] == '', 'tags'] = np.nan

df_lst['username'].isnull().sum()

df_lst['comments'] = df_lst['comments'].astype(str)
df_lst['username'] = df_lst['username'].astype(str)
df_lst['tags'] = df_lst['tags'].astype(str)

df_lst = df_lst.fillna('Null')
df_lst

# 작은 따옴표를 기준으로 문자열 나눠서 리스트로 저장
for i in range(df_lst.shape[0]):
    df_lst['comments'][i] = re.split("'([^']*)'", df_lst['comments'][i])
    df_lst['username'][i] = re.split("'([^']*)'", df_lst['username'][i])
    df_lst['tags'][i] = re.split("'([^']*)'", df_lst['tags'][i])

df_lst['comments'][0]

df_lst['tags'][0]

if '':
    print(True)
else:
    print(False)

# 리스트에서 빈 문자열 삭제 위의 예시 확인
for i in range(df_lst.shape[0]):
    df_lst['comments'][i] = [v for v in df_lst['comments'][i] if v]
    df_lst['username'][i] = [v for v in df_lst['username'][i] if v]
    df_lst['tags'][i] = [v for v in df_lst['tags'][i] if v]

df_lst['username'][0]

df_lst

"""#### 광고 게시글만 분리
광고, 협찬, 제품제공, sponsored, 추천인, 추천인코드, 공구, 공동구매, ad, 제품협찬
"""

df_lst['tags'][0]

df_lst['tags'][0].__contains__('nan')

# 해당 태그가 들어간 글 분류
lst = ['#광고', '#협찬', '#제공', '#sponsored', '#추천인', '#추천인코드',
       '#공구', '#공동구매', '#ad', '#제품제공', '#할인코드', '#제품협찬',
       '#재품제공', '#유료광고', '#제품증정광고', '#제품제공광고', '#지원', '#숙소지원',
       '#홍보', '#서포터즈', '#제휴', '#유료광고', '#대가성광고', '#AD',
       ]

ad_lst = []
for i in range(df_lst.shape[0]):
    ad = 0
    for ad_tag in lst:
        if df_lst['tags'][i].__contains__(ad_tag):
            ad += 1
    if ad:
        ad_lst.append(i)

len(ad_lst)

df_ad_1 = df_lst.iloc[ad_lst].reset_index(drop=True)
df_ad_1

df_lst = df_lst.drop(index=ad_lst).reset_index(drop=True)
df_lst

df_str = df_str.drop(index=ad_lst).reset_index(drop=True)
df_str

# 해당 단어가 들어가 있는 태그를 찾아 글 분류
lst = ['이벤트', '공구', '포터즈', '링크']

ad_lst = []
for i in range(df_lst.shape[0]):
    ad = 0
    for tag in df_lst['tags'][i]:
        for ad_tag in lst:
            if tag.find(ad_tag) != -1:
                ad += 1
    if ad:
        ad_lst.append(i)

if -1:
    print(True)

len(ad_lst)

df_ad_2 = df_lst.iloc[ad_lst].reset_index(drop=True)
df_ad_2

df_lst = df_lst.drop(index=ad_lst).reset_index(drop=True)
df_lst

df_str = df_str.drop(index=ad_lst).reset_index(drop=True)
df_str

df_ad = pd.concat([df_ad_1, df_ad_2]).reset_index(drop=True)
df_ad

ad_list_1 = list(df_str.loc[df_str['content'].str.startswith('광고')].index)
len(ad_list_1)

df_ad_3 = df_str.iloc[ad_list_1]

df_lst = df_lst.drop(index = ad_list_1).reset_index(drop=True)
df_str = df_str.drop(index = ad_list_1).reset_index(drop=True)

ad_list_2 = list(df_str.loc[df_str['content'].str.startswith('협찬')].index)
len(ad_list_2)

df_ad_4 = df_str.iloc[ad_list_2]

df_lst = df_lst.drop(index = ad_list_2).reset_index(drop=True)
df_str = df_str.drop(index = ad_list_2).reset_index(drop=True)

df_ad = pd.concat([df_ad, df_ad_3, df_ad_4]).reset_index(drop=True)
df_ad

ad_list_3 = list(df_str.loc[df_str['content'].str.startswith('제품제공')].index)
len(ad_list_3)

df_ad_5 = df_str.iloc[ad_list_3]

df_lst = df_lst.drop(index = ad_list_3).reset_index(drop=True)
df_str = df_str.drop(index = ad_list_3).reset_index(drop=True)

df_ad = pd.concat([df_ad, df_ad_5]).reset_index(drop=True)
df_ad

df_str['comments'] = df_str['comments'].astype(str)
df_str['username'] = df_str['username'].astype(str)
df_str['tags'] = df_str['tags'].astype(str)

tag_lst = ['광고', '협찬', '제공', '지원']
ad_lst = []
for i in range(df_str.shape[0]):
    ad = 0
    for tag in tag_lst:
        if df_str['tags'][i].find(tag) != -1:
            ad += 1
    if ad:
        ad_lst.append(i)

len(ad_lst)

no_ad_list = [0,28,1493,1536,2785, 6292, 6311, 7002, 18953,19563,19564,19569,19570,19571,19572,19574,19576,19577,19578,19579, 20643, 23806, 24677, 24701, 24702, 24716, 11485, 11691, 12469, 12706, 14358, 14360, 14371, 14382, 16750,
       16753]

for no_ad in no_ad_list:
    ad_lst.remove(no_ad)

df_ad_6 = df_str.iloc[ad_lst]

df_ad = pd.concat([df_ad, df_ad_6]).reset_index(drop=True)
df_ad

df_lst = df_lst.drop(index = ad_lst).reset_index(drop=True)
df_str = df_str.drop(index = ad_lst).reset_index(drop=True)

word_lst = ['추천인', '공구', '코드', '광고', '협찬', '지원', '제공', '이벤트', '초대', '링크', '프로모션', '공동구매']

ad_lst = []
for i in range(df_str.shape[0]):
    ad = 0
    for word in word_lst:
        if df_str['content'][i].find(word) != -1:
            ad += 1
    if ad:
        ad_lst.append(i)

len(ad_lst)

h = pd.read_csv(f"{DATA_PATH}김현경.csv")
j = pd.read_csv(f"{DATA_PATH}박지혜.csv")
k = pd.read_csv(f"{DATA_PATH}박경봉.csv")
d = pd.read_csv(f"{DATA_PATH}이동규.csv")
s = pd.read_csv(f"{DATA_PATH}한수길.csv")
c = pd.read_csv(f"{DATA_PATH}최성진.csv")

h_lst = list(h[h['ad'] == 1]['Unnamed: 0'].values)
j_lst = list(j[j['ad'] == 1]['Unnamed: 0'].values)
k_lst = list(k[k['Unnamed: 9'] == 1]['Unnamed: 0'].values)
d_lst = list(d[d['ad'] == 1]['Unnamed: 0'].values)
s_lst = list(s[s['ad'] == 1]['Unnamed: 0'].values)
c_lst = list(c[c['ad'] == 1]['Unnamed: 0'].values)

ad_lst = h_lst + j_lst + k_lst + d_lst + s_lst + c_lst

df_ad_7 = df_str.iloc[ad_lst]
df_ad_7

df_ad = pd.concat([df_ad, df_ad_7]).reset_index(drop=True)
df_ad

df_lst = df_lst.drop(index = ad_lst).reset_index(drop=True)
df_str = df_str.drop(index = ad_lst).reset_index(drop=True)

df_lst

df_str

df_ad.to_csv(f"{DATA_PATH}AD_LIST_2.csv", encoding='utf-8-sig', index=False)
df_str.to_csv(f"{DATA_PATH}NO_AD_LIST_STR_2.csv", encoding='utf-8-sig', index=False)
df_lst.to_csv(f"{DATA_PATH}NO_AD_LIST_LST_2.csv", encoding='utf-8-sig', index=False)